version: '3'
services:
  service:
    image: meicm-project1
    build:
        context: ./src/
        dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    env_file:
      - .env